# Generated by Django 5.0.7 on 2024-07-29 17:20

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllergensWarning",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("description", models.CharField(max_length=10240, unique=True)),
            ],
            options={
                "verbose_name": "Allergens Warning",
                "verbose_name_plural": "Allergens Warnings",
                "db_table": "allergens_warnings",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BreadCrumb",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("breadcrumb_content", models.TextField(unique=True)),
                (
                    "breadcrumb_array",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bread Crumb",
                "verbose_name_plural": "Bread Crumbs",
                "db_table": "bread_crumbs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Bullet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "description",
                    models.CharField(
                        db_collation="english_ci", max_length=10240, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Bullet",
                "verbose_name_plural": "Bullets",
                "db_table": "bullets",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DietaryInformation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("description", models.CharField(max_length=10240, unique=True)),
            ],
            options={
                "verbose_name": "Dietary Information",
                "verbose_name_plural": "Dietary Information",
                "db_table": "dietary_informations",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=512, unique=True)),
            ],
            options={
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturers",
                "db_table": "manufacturers",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PriceUnit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=512, unique=True)),
            ],
            options={
                "verbose_name": "Price Unit",
                "verbose_name_plural": "Price Units",
                "db_table": "price_units",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=512, unique=True)),
            ],
            options={
                "verbose_name": "Storage",
                "verbose_name_plural": "Storages",
                "db_table": "storages",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=512, unique=True)),
                ("description", models.CharField(max_length=512)),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
                "db_table": "units",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=512)),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "db_table": "brands",
                "managed": True,
                "unique_together": {("name", "deleted")},
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=512)),
                ("code", models.CharField(max_length=256)),
                (
                    "scheme",
                    models.CharField(
                        blank=True, db_collation="english_ci", max_length=256, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "managed": True,
                "unique_together": {("code", "scheme"), ("name", "scheme")},
            },
        ),
        migrations.CreateModel(
            name="CategoryPrediction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "predicted_category_name",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "model_version",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "manual_category_name",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("verified", models.BooleanField()),
                (
                    "verified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "manual_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categorypredictions_manual_category_set",
                        to="food_labels.category",
                    ),
                ),
                (
                    "predicted_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Prediction",
                "verbose_name_plural": "Category Predictions",
                "db_table": "category_predictions",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CategoryReportData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("product_count", models.IntegerField()),
                (
                    "predicted_category_count",
                    models.IntegerField(blank=True, null=True),
                ),
                ("manual_category_count", models.IntegerField(blank=True, null=True)),
                ("sodium_ranking", models.IntegerField(blank=True, null=True)),
                ("saturated_fat_ranking", models.IntegerField(blank=True, null=True)),
                ("sugar_ranking", models.IntegerField(blank=True, null=True)),
                (
                    "ingredient_upper_quantile_count",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "ingredient_lower_quantile_count",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Report Data",
                "verbose_name_plural": "Category Report Data",
                "db_table": "category_report_data",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=512, unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="food_labels.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "db_table": "companies",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("nutrient_code", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=256, unique=True)),
                ("symbol", models.CharField(max_length=256)),
                ("usda_nutrient_code", models.IntegerField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.nutrient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutrient",
                "verbose_name_plural": "Nutrients",
                "db_table": "nutrients",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(db_collation="english_ci", max_length=512)),
            ],
            options={
                "verbose_name": "Source",
                "verbose_name_plural": "Sources",
                "db_table": "sources",
                "managed": True,
                "unique_together": {("name", "deleted")},
            },
        ),
        migrations.CreateModel(
            name="ProductProfile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.brand",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.company",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.manufacturer",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Profile",
                "verbose_name_plural": "Product Profiles",
                "db_table": "product_profiles",
                "managed": True,
                "unique_together": {("name", "brand", "company")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("variety_pack_flag", models.BooleanField()),
                ("nielsen_product_flag", models.BooleanField()),
                (
                    "private_label",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "atwater_result",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("total_size", models.CharField(blank=True, max_length=512, null=True)),
                ("serving_size", models.IntegerField(blank=True, null=True)),
                ("ingredient_en", models.TextField(blank=True, null=True)),
                ("ingredient_fr", models.TextField(blank=True, null=True)),
                (
                    "name_of_product",
                    models.CharField(
                        blank=True, db_collation="english_ci", max_length=512, null=True
                    ),
                ),
                (
                    "description_of_product",
                    models.CharField(
                        blank=True,
                        db_collation="english_ci",
                        max_length=10240,
                        null=True,
                    ),
                ),
                ("total_size_value", models.IntegerField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.category",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.product",
                    ),
                ),
                (
                    "product_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.productprofile",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=512)),
            ],
            options={
                "verbose_name": "Store",
                "verbose_name_plural": "Stores",
                "db_table": "stores",
                "managed": True,
                "unique_together": {("name", "deleted")},
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("scrape_datetime", models.DateTimeField()),
                ("total_number_of_products", models.IntegerField()),
                ("total_number_of_new_products", models.IntegerField()),
                ("total_number_of_missing_products", models.IntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("region", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, db_collation="english_ci", max_length=10, null=True
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
                "db_table": "scrape_batches",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StoreProduct",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("store_product_code", models.CharField(max_length=512)),
                ("sku", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "reading_price",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("price", models.FloatField(blank=True, null=True)),
                ("company_id", models.IntegerField(blank=True, null=True)),
                (
                    "raw_brand",
                    models.CharField(
                        blank=True, db_collation="english_ci", max_length=256, null=True
                    ),
                ),
                ("site_url", models.TextField(blank=True, null=True)),
                (
                    "site_name",
                    models.CharField(
                        blank=True, db_collation="english_ci", max_length=512, null=True
                    ),
                ),
                (
                    "site_description",
                    models.CharField(
                        blank=True,
                        db_collation="english_ci",
                        max_length=10240,
                        null=True,
                    ),
                ),
                ("most_recent_flag", models.BooleanField()),
                (
                    "private_label",
                    models.CharField(
                        blank=True,
                        db_collation="english_ci",
                        max_length=4096,
                        null=True,
                    ),
                ),
                ("nutrition_available_flag", models.BooleanField()),
                ("nutrition_facts_json", models.JSONField(blank=True, null=True)),
                ("total_size", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "raw_serving_size",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("serving_size", models.IntegerField(blank=True, null=True)),
                ("ingredient_en", models.TextField(blank=True, null=True)),
                ("ingredient_fr", models.TextField(blank=True, null=True)),
                (
                    "raw_upc",
                    models.CharField(
                        blank=True, db_collation="english_ci", max_length=512, null=True
                    ),
                ),
                ("verified", models.BooleanField()),
                (
                    "verified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "atwater_result",
                    models.CharField(
                        blank=True, db_collation="english_ci", max_length=64, null=True
                    ),
                ),
                (
                    "nielsen_upc",
                    models.CharField(
                        blank=True, db_collation="english_ci", max_length=124, null=True
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        db_collation="english_ci",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "bread_crumb",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.breadcrumb",
                    ),
                ),
                (
                    "category_prediction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.categoryprediction",
                    ),
                ),
                (
                    "price_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.priceunit",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.product",
                    ),
                ),
                (
                    "scrape_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.batch",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.source",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="food_labels.storage",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Product",
                "verbose_name_plural": "Store Products",
                "db_table": "store_products",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StoreProductAllergensWarning",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "allergens_warning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.allergenswarning",
                    ),
                ),
                (
                    "store_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.storeproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "SP Allergens Warning",
                "verbose_name_plural": "SP Allergens Warnings",
                "db_table": "store_product_allergens_warnings",
                "managed": True,
                "unique_together": {("store_product", "allergens_warning")},
            },
        ),
        migrations.AddField(
            model_name="storeproduct",
            name="allergens_warnings",
            field=models.ManyToManyField(
                through="food_labels.StoreProductAllergensWarning",
                to="food_labels.allergenswarning",
            ),
        ),
        migrations.CreateModel(
            name="StoreProductBullet",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "bullet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.bullet",
                    ),
                ),
                (
                    "store_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.storeproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "SP Bullet",
                "verbose_name_plural": "SP Bullets",
                "db_table": "store_product_bullets",
                "managed": True,
                "unique_together": {("store_product", "bullet")},
            },
        ),
        migrations.AddField(
            model_name="storeproduct",
            name="bullets",
            field=models.ManyToManyField(
                through="food_labels.StoreProductBullet", to="food_labels.bullet"
            ),
        ),
        migrations.CreateModel(
            name="StoreProductDietaryInfo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "dietary_information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.dietaryinformation",
                    ),
                ),
                (
                    "store_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.storeproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "SP Dietary Information",
                "verbose_name_plural": "SP Dietary Information",
                "db_table": "store_product_dietary_infos",
                "managed": True,
                "unique_together": {("store_product", "dietary_information")},
            },
        ),
        migrations.AddField(
            model_name="storeproduct",
            name="dietary_informations",
            field=models.ManyToManyField(
                through="food_labels.StoreProductDietaryInfo",
                to="food_labels.dietaryinformation",
            ),
        ),
        migrations.CreateModel(
            name="StoreProductNutritionFact",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("daily_value", models.FloatField(blank=True, null=True)),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.nutrient",
                    ),
                ),
                (
                    "store_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.storeproduct",
                    ),
                ),
                (
                    "amount_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "SP Nutrition Fact",
                "verbose_name_plural": "SP Nutrition Facts",
                "db_table": "store_product_nutrition_facts",
                "managed": True,
                "unique_together": {("store_product", "nutrient")},
            },
        ),
        migrations.AddField(
            model_name="storeproduct",
            name="nutrients",
            field=models.ManyToManyField(
                through="food_labels.StoreProductNutritionFact",
                to="food_labels.nutrient",
            ),
        ),
        migrations.CreateModel(
            name="StoreReportData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("nutrition_fact_count", models.IntegerField(blank=True, null=True)),
                ("ingredient_list_count", models.IntegerField(blank=True, null=True)),
                ("contains_image_count", models.IntegerField(blank=True, null=True)),
                ("allergen_warning_count", models.IntegerField(blank=True, null=True)),
                ("complete_product_count", models.IntegerField(blank=True, null=True)),
                ("product_count", models.IntegerField()),
                (
                    "predicted_category_count",
                    models.IntegerField(blank=True, null=True),
                ),
                ("manual_category_count", models.IntegerField(blank=True, null=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Report Data",
                "verbose_name_plural": "Store Report Data",
                "db_table": "store_report_data",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=512)),
                ("code", models.CharField(max_length=256)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcategory",
                "verbose_name_plural": "Subcategories",
                "db_table": "subcategories",
                "managed": True,
                "unique_together": {("category", "code"), ("category", "name")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="food_labels.subcategory",
            ),
        ),
        migrations.CreateModel(
            name="SubcategoryPrediction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "predicted_subcategory_name",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "model_version",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "manual_subcategory_name",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("verified", models.BooleanField()),
                ("verified_by", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "manual_subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategorypredictions_manual_subcategory_set",
                        to="food_labels.subcategory",
                    ),
                ),
                (
                    "predicted_subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcategory Prediction",
                "verbose_name_plural": "Subcategories Predictions",
                "db_table": "subcategory_predictions",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="storeproduct",
            name="subcategory_prediction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="food_labels.subcategoryprediction",
            ),
        ),
        migrations.CreateModel(
            name="SubcategoryReportData",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("product_count", models.IntegerField()),
                (
                    "predicted_category_count",
                    models.IntegerField(blank=True, null=True),
                ),
                ("manual_category_count", models.IntegerField(blank=True, null=True)),
                ("sodium_ranking", models.IntegerField(blank=True, null=True)),
                ("saturated_fat_ranking", models.IntegerField(blank=True, null=True)),
                ("sugar_ranking", models.IntegerField(blank=True, null=True)),
                (
                    "ingredient_upper_quantile_count",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "ingredient_lower_quantile_count",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcategory Report Data",
                "verbose_name_plural": "Subcategories Report Data",
                "db_table": "subcategory_report_data",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="storeproduct",
            name="serving_size_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="food_labels.unit",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="serving_size_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="food_labels.unit",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="total_size_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products_total_size_unit_set",
                to="food_labels.unit",
            ),
        ),
        migrations.CreateModel(
            name="UPC",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "code",
                    models.CharField(
                        db_collation="english_ci", max_length=128, unique=True
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "UPC",
                "verbose_name_plural": "UPCs",
                "db_table": "upcs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StoreProductImage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "label",
                    models.CharField(
                        blank=True, db_collation="english_ci", max_length=250, null=True
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "image_path",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "store_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.storeproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "SP Image",
                "verbose_name_plural": "SP Images",
                "db_table": "store_product_images",
                "managed": True,
                "unique_together": {("label", "number", "store_product")},
            },
        ),
        migrations.CreateModel(
            name="ProductNutritionFact",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("daily_value", models.FloatField(blank=True, null=True)),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.nutrient",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.product",
                    ),
                ),
                (
                    "amount_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Nutrition Fact",
                "verbose_name_plural": "Product Nutrition Facts",
                "db_table": "product_nutrition_facts",
                "managed": True,
                "unique_together": {("product", "nutrient")},
            },
        ),
        migrations.CreateModel(
            name="ProductUPC",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("deleted_datetime", models.DateTimeField(blank=True, null=True)),
                ("deleted_by", models.CharField(blank=True, max_length=256, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.product",
                    ),
                ),
                (
                    "upc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_labels.upc",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product UPC",
                "verbose_name_plural": "Product UPCs",
                "db_table": "product_upcs",
                "managed": True,
                "unique_together": {("product", "upc")},
            },
        ),
    ]
