# Generated by Django 5.0.7 on 2024-08-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_labels", "0006_move_subcategory_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="products", to="food_labels.category"
            ),
        ),
    ]
