# Generated by Django 5.0.7 on 2024-08-14 15:13
from django.db import migrations


def populate_product_categories(apps, schema_editor):
    Product = apps.get_model('food_labels', 'Product')
    Category = apps.get_model('food_labels', 'Category')

    for product in Product.objects.all():
        if product.subcategory is None:
            print(f"Warning: Product {product.id} has no subcategory. Skipping.")
            continue

        # Get the corresponding category (which was created from the subcategory)
        category = Category.objects.filter(
            name=product.subcategory.name,
            code=product.subcategory.code,
            parent_category=product.subcategory.category,
            level=2
        ).first()

        if category:
            product.categories.add(category)
            
            # Also add the parent category
            if category.parent_category:
                product.categories.add(category.parent_category)
        else:
            print(f"Warning: No matching category found for product {product.id} with subcategory {product.subcategory.name}. Skipping.")


def reverse_populate_product_categories(apps, schema_editor):
    Product = apps.get_model('food_labels', 'Product')
    Product.objects.all().update(categories=None)


class Migration(migrations.Migration):

    dependencies = [
        ('food_labels', '0007_alter_category_unique_together_product_categories'),
    ]

    operations = [
        migrations.RunPython(populate_product_categories, reverse_populate_product_categories),
    ]


