# Generated by Django 5.0.7 on 2024-08-15 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food_labels", "0008_populate_product_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="subcategory",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.DeleteModel(
            name="Subcategory",
        ),
    ]
