# Generated by Django 5.0.7 on 2024-08-21 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_labels", "0009_remove_product_subcategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storeproduct",
            name="company_id",
        ),
        migrations.AddField(
            model_name="storeproduct",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="food_labels.company",
            ),
        ),
    ]
