# Generated by Django 5.0.7 on 2024-09-10 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_labels", "0010_alter_category_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="food_labels.category",
            ),
        ),
        migrations.AlterField(
            model_name="storeproductnutritionfact",
            name="store_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nutrition_facts",
                to="food_labels.storeproduct",
            ),
        ),
    ]
