# Generated by Django 5.0.7 on 2024-09-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_labels", "0011_alter_category_children_and_nft"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeproduct",
            name="external_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="storeproduct",
            name="verified_nft_ingredients",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("manually_entered", "Manually Entered"),
                    ("ocr_verified", "OCR (Manually Verified)"),
                    ("ocr_unverified", "OCR (Unverified)"),
                    ("external", "External"),
                ],
                default="unknown",
                max_length=20,
                verbose_name="Verified NFT/Ingredients",
            ),
        ),
    ]
