# Generated by Django 5.0.7 on 2024-09-19 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food_labels", "0012_add_external_id_and_verified"),
    ]


    operations = [
        migrations.RunSQL(
            sql='''
            -- Drop all notify and truncate triggers
            DROP TRIGGER IF EXISTS bread_crumbs_notify ON bread_crumbs;
            DROP TRIGGER IF EXISTS bread_crumbs_truncate ON bread_crumbs;
            DROP TRIGGER IF EXISTS categories_notify ON categories;
            DROP TRIGGER IF EXISTS categories_truncate ON categories;
            DROP TRIGGER IF EXISTS dietary_informations_notify ON dietary_informations;
            DROP TRIGGER IF EXISTS dietary_informations_truncate ON dietary_informations;
            DROP TRIGGER IF EXISTS nutrients_notify ON nutrients;
            DROP TRIGGER IF EXISTS nutrients_truncate ON nutrients;
            DROP TRIGGER IF EXISTS products_notify ON products;
            DROP TRIGGER IF EXISTS products_truncate ON products;
            DROP TRIGGER IF EXISTS scrape_batches_notify ON scrape_batches;
            DROP TRIGGER IF EXISTS scrape_batches_truncate ON scrape_batches;
            DROP TRIGGER IF EXISTS sources_notify ON sources;
            DROP TRIGGER IF EXISTS sources_truncate ON sources;
            DROP TRIGGER IF EXISTS store_product_dietary_infos_notify ON store_product_dietary_infos;
            DROP TRIGGER IF EXISTS store_product_dietary_infos_truncate ON store_product_dietary_infos;
            DROP TRIGGER IF EXISTS store_product_nutrition_facts_notify ON store_product_nutrition_facts;
            DROP TRIGGER IF EXISTS store_product_nutrition_facts_truncate ON store_product_nutrition_facts;
            DROP TRIGGER IF EXISTS stores_notify ON stores;
            DROP TRIGGER IF EXISTS stores_truncate ON stores;
            DROP TRIGGER IF EXISTS units_notify ON units;
            DROP TRIGGER IF EXISTS units_truncate ON units;
            DROP TRIGGER IF EXISTS store_product_images_notify ON store_product_images;
            DROP TRIGGER IF EXISTS store_product_images_truncate ON store_product_images;
            DROP TRIGGER IF EXISTS store_products_notify ON store_products;
            DROP TRIGGER IF EXISTS store_products_truncate ON store_products;

            -- Drop the table_notify function
            DROP FUNCTION IF EXISTS public.table_notify();
            ''',
            reverse_sql=migrations.RunSQL.noop
        ),
    ]