# Generated by Django 5.0.7 on 2024-09-19 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food_labels", "0014_restrict_to_cascade"),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            ALTER TABLE store_product_bullets
            DROP CONSTRAINT IF EXISTS "FK_store_product_bullets_bullets_bullet_id",
            ADD CONSTRAINT "FK_store_product_bullets_bullets_bullet_id"
            FOREIGN KEY (bullet_id)
            REFERENCES bullets(id)
            ON DELETE CASCADE;

            ALTER TABLE store_product_bullets
            DROP CONSTRAINT IF EXISTS "FK_store_product_bullets_store_products_store_product_id",
            ADD CONSTRAINT "FK_store_product_bullets_store_products_store_product_id"
            FOREIGN KEY (store_product_id)
            REFERENCES store_products(id)
            ON DELETE CASCADE;
            ''',
            reverse_sql='''
            ALTER TABLE store_product_bullets
            DROP CONSTRAINT IF EXISTS "FK_store_product_bullets_bullets_bullet_id",
            ADD CONSTRAINT "FK_store_product_bullets_bullets_bullet_id"
            FOREIGN KEY (bullet_id)
            REFERENCES bullets(id)
            ON DELETE RESTRICT;

            ALTER TABLE store_product_bullets
            DROP CONSTRAINT IF EXISTS "FK_store_product_bullets_store_products_store_product_id",
            ADD CONSTRAINT "FK_store_product_bullets_store_products_store_product_id"
            FOREIGN KEY (store_product_id)
            REFERENCES store_products(id)
            ON DELETE RESTRICT;
            '''
        ),
    ]
