# Generated by Django 4.2.3 on 2024-10-17 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("food_labels", "0016_update_constraints_forreal"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="reference_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="reference_amount_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_reference_amount_unit_set",
                to="food_labels.unit",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplemented_food",
            field=models.BooleanField(default=False),
        ),
    ]
