# Generated by Django 4.2.3 on 2025-03-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_labels", "0017_add_ra_and_suppfood_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="productnutritionfact",
            name="supplemented",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storeproductnutritionfact",
            name="supplemented",
            field=models.BooleanField(default=False),
        ),
    ]
