# Generated by Django 4.2.3 on 2025-01-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_labels", "0024_setup_initial_schemes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="bullet",
            name="description",
            field=models.CharField(max_length=10240, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_of_product",
            field=models.CharField(blank=True, max_length=10240, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_of_product",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="storeproduct",
            name="atwater_result",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="storeproduct",
            name="nielsen_upc",
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name="storeproduct",
            name="private_label",
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name="storeproduct",
            name="raw_brand",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="storeproduct",
            name="raw_upc",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="storeproduct",
            name="site_description",
            field=models.CharField(blank=True, max_length=10240, null=True),
        ),
        migrations.AlterField(
            model_name="storeproduct",
            name="site_name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="storeproduct",
            name="tags",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="storeproductimage",
            name="label",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="upc",
            name="code",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
