# Generated by Django 4.2.3 on 2025-04-23 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food_labels", "0019_add_nutrients_and_units"),
        ("food_labels", "0025_remove_english_ci_collation"),
    ]

    operations = []
