# Generated by Django 4.2.3 on 2025-07-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_labels", "0026_merge_20250423_1020"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="individually_packaged_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storeproduct",
            name="manual_verification_reason",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="storeproduct",
            name="needs_manual_verification",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="storeproduct",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
