# Generated by Django 4.2.3 on 2025-08-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("food_labels", "0027_alter_category_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuppFoodLabelFlags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_supplemental_caution_id", models.BooleanField(default=False)),
                ("has_nutrient_content_claim", models.BooleanField(default=False)),
                ("has_nutrient_function_claim", models.BooleanField(default=False)),
                (
                    "has_disease_risk_reduction_claim",
                    models.BooleanField(default=False),
                ),
                ("has_probiotic_claim", models.BooleanField(default=False)),
                ("has_therapeutic_claim", models.BooleanField(default=False)),
                ("has_function_claim", models.BooleanField(default=False)),
                ("has_general_health_claim", models.BooleanField(default=False)),
                (
                    "has_quantitative_nutrient_declaration",
                    models.BooleanField(default=False),
                ),
                ("has_implied_nonspecific_claim", models.BooleanField(default=False)),
                ("has_logos_icons", models.BooleanField(default=False)),
                ("has_third_party_label", models.BooleanField(default=False)),
                (
                    "store_product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_flags",
                        to="food_labels.storeproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Label Flags for Supplemented Foods",
                "verbose_name_plural": "Label Flags for Supplemented Foods",
                "db_table": "supp_food_label_flags",
                "managed": True,
            },
        ),
    ]
