# Generated by Django 4.2.3 on 2025-09-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_labels", "0028_create_supp_food_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualproductcategory",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
