# Generated by Django 5.0.7 on 2025-11-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_labels', '0029_create_manual_category_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnutritionfact',
            name='nft_label',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='multiple_nfts_flag',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeproductnutritionfact',
            name='nft_label',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='verified',
            field=models.BooleanField(verbose_name='Entire product manually verified'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='verified_nft_ingredients',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('manually_entered', 'Manually Entered'), ('ocr_verified', 'OCR (Manually Verified)'), ('ocr_unverified', 'OCR (Unverified)'), ('external', 'External')], default='unknown', max_length=20, verbose_name='Verified NFT'),
        ),
    ]
