# Generated by Django 5.0.7 on 2025-11-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_labels', '0030_multiple_nfts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='fop_flag',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='has_preparation_instructions_flag',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='individually_packged_flag',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
