# Generated by Django 4.2.3 on 2025-12-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_labels", "0031_storeproduct_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeproduct",
            name="primary_package_material",
            field=models.CharField(
                choices=[
                    ("glass", "Glass"),
                    ("metal", "Metal"),
                    ("paper", "Paper/paperboard"),
                    ("plastic_pet", "Plastic - PET - 1"),
                    ("plastic_hdpe", "Plastic - HDPE - 2"),
                    ("plastic_pvc", "Plastic - PVC - 3"),
                    ("plastic_ldpe", "Plastic - LDPE - 4"),
                    ("plastic_pp", "Plastic - PP - 5"),
                    ("plastic_ps", "Plastic - PS - 6"),
                    ("plastic_other", "Plastic - OTHER - 7"),
                    ("plastic_unknown", "Plastic - Unknown"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
                verbose_name="Primary Package Material",
            ),
        ),
        migrations.AddField(
            model_name="storeproduct",
            name="secondary_package_material",
            field=models.CharField(
                blank=True,
                choices=[
                    ("glass", "Glass"),
                    ("metal", "Metal"),
                    ("paper", "Paper/paperboard"),
                    ("plastic_pet", "Plastic - PET - 1"),
                    ("plastic_hdpe", "Plastic - HDPE - 2"),
                    ("plastic_pvc", "Plastic - PVC - 3"),
                    ("plastic_ldpe", "Plastic - LDPE - 4"),
                    ("plastic_pp", "Plastic - PP - 5"),
                    ("plastic_ps", "Plastic - PS - 6"),
                    ("plastic_other", "Plastic - OTHER - 7"),
                    ("plastic_unknown", "Plastic - Unknown"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
                verbose_name="Secondary Package Material",
            ),
        ),
        migrations.AddField(
            model_name="storeproduct",
            name="storage_condition",
            field=models.CharField(
                choices=[
                    ("shelf_stable", "Shelf Stable"),
                    ("fridge", "Fridge"),
                    ("freezer", "Freezer"),
                ],
                default="shelf_stable",
                max_length=20,
                verbose_name="Storage Condition",
            ),
        ),
    ]
