# Generated by Django 4.2.3 on 2026-01-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_labels", "0032_add_storage_packaging"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeproduct",
            name="num_units",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number of Units"
            ),
        ),
    ]
