# Generated by Django 4.2.3 on 2026-01-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_labels", "0033_add_num_units"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allergenswarning",
            name="description",
        ),
        migrations.AddField(
            model_name="allergenswarning",
            name="contains_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allergenswarning",
            name="contains_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allergenswarning",
            name="may_contain_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allergenswarning",
            name="may_contain_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="allergenswarning",
            constraint=models.UniqueConstraint(
                fields=(
                    "contains_en",
                    "contains_fr",
                    "may_contain_en",
                    "may_contain_fr",
                ),
                name="unique_allergen_combination",
            ),
        ),
    ]
