# Generated by Django 5.0.7 on 2026-07-31 15:51
"""Bring Django's model state in line with the FSDH database.

This migration describes the schema exactly as the nutrient-migration scripts
(migrate.py / phase2.py / phase3.py) left it: the products table and its
satellites are gone, category labels and UPCs hang off store_products, and the
individually_packged_flag typo is fixed.

APPLYING THIS:
  * Fresh database (local dev, CI, test runs) — run it normally; it builds the
    post-migration schema from 0034.
  * The FSDH database (fsdh-flaime-psql-prd-001 / fsdh) — the scripts already
    made every one of these changes, so fake it:
        python manage.py migrate food_labels 0035 --fake
    Then run 0036 for real; that one carries the changes the scripts did NOT make.

Note: bread_crumbs and product_nutrition_facts are deleted from Django's state
here, but their tables still exist on the FSDH database — phase3.py's
drop_legacy_tables step drops them and has not been run yet.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_labels', '0034_alter_allergens_warning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproduct',
            name='bread_crumb',
        ),
        migrations.RemoveField(
            model_name='manualproductcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='manualproductcategory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='manualproductcategory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productprofile',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='predictedproductcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='predictedproductcategory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='storeproduct',
            name='price_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_profile',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reference_amount_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='serving_size_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='source',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_size_unit',
        ),
        migrations.RemoveField(
            model_name='productupc',
            name='product',
        ),
        migrations.RemoveField(
            model_name='storeproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productnutritionfact',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productnutritionfact',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productnutritionfact',
            name='amount_unit',
        ),
        migrations.RemoveField(
            model_name='productnutritionfact',
            name='nutrient',
        ),
        migrations.AlterUniqueTogether(
            name='productprofile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productprofile',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='productprofile',
            name='source',
        ),
        migrations.AlterUniqueTogether(
            name='productupc',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productupc',
            name='upc',
        ),
        migrations.RemoveField(
            model_name='storeproduct',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='storereportdata',
            name='store',
        ),
        migrations.RenameField(
            model_name='storeproduct',
            old_name='individually_packged_flag',
            new_name='individually_packaged_flag',
        ),
        migrations.RemoveField(
            model_name='storeproduct',
            name='most_recent_flag',
        ),
        migrations.RemoveField(
            model_name='storeproduct',
            name='reading_price',
        ),
        migrations.RemoveField(
            model_name='storeproduct',
            name='site_url',
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_labels.brand'),
        ),
        migrations.CreateModel(
            name='StoreProductManualCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('problematic_flag', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_labels.category')),
                ('store_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_categories', to='food_labels.storeproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manually Verified Category',
                'verbose_name_plural': 'Manually Verified Categories',
                'db_table': 'store_product_manual_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StoreProductPredictedCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_id', models.CharField(max_length=256)),
                ('date_predicted', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_labels.category')),
                ('store_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_categories', to='food_labels.storeproduct')),
            ],
            options={
                'verbose_name': 'Predicted Store Product Category',
                'verbose_name_plural': 'Predicted Store Product Categories',
                'db_table': 'store_product_predicted_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StoreProductUPC',
            fields=[
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=256, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted_datetime', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('store_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_labels.storeproduct')),
                ('upc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_labels.upc')),
            ],
            options={
                'verbose_name': 'SP UPC',
                'verbose_name_plural': 'SP UPCs',
                'db_table': 'store_product_upcs',
                'managed': True,
                'unique_together': {('store_product', 'upc')},
            },
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='upcs',
            field=models.ManyToManyField(through='food_labels.StoreProductUPC', to='food_labels.upc'),
        ),
        migrations.DeleteModel(
            name='BreadCrumb',
        ),
        migrations.DeleteModel(
            name='ManualProductCategory',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='PredictedProductCategory',
        ),
        migrations.DeleteModel(
            name='PriceUnit',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductNutritionFact',
        ),
        migrations.DeleteModel(
            name='ProductProfile',
        ),
        migrations.DeleteModel(
            name='ProductUPC',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.DeleteModel(
            name='StoreReportData',
        ),
    ]
