# Generated by Django 5.0.7 on 2026-08-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_labels', '0034_alter_allergens_warning'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='allergenswarning',
            name='unique_allergen_combination',
        ),
    ]
