# Generated by Django 5.0.7 on 2026-08-31 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_labels', '0035_remove_allergenswarning_unique_allergen_combination'),
        ('food_labels', '0036_storeproduct_supplemented_food_variety_pack'),
    ]

    operations = [
    ]
