# Generated by Django 5.0.7 on 2026-09-24 17:31
"""Track location per store product, and give the structured size fields a home.

* Location used to be recorded on the batch (scrape_batches.region). It is now a
  per-product FK to a small `locations` table, seeded here with Ontario and Quebec.
  Store was already per product (store_products.store_id) and is unchanged.
* total_size_value / total_size_unit and reference_amount / reference_amount_unit
  lived on the old `products` table and were lost when the FSDH migration dropped
  it. The columns are added empty here; nutrient-migration's `migrate.py finalize`
  fills them from the legacy snapshot.

Note: makemigrations also emits an AlterUniqueTogether(category, set()) because
the Category model no longer declares the unique_together the migration history
has. That drift is pre-existing and unrelated, so it was removed from this file.
"""

import django.db.models.deletion
from django.db import migrations, models


LOCATIONS = [
    ("Ontario", "ON"),
    ("Quebec", "QC"),
]


def seed_locations(apps, schema_editor):
    Location = apps.get_model("food_labels", "Location")
    for name, code in LOCATIONS:
        Location.objects.get_or_create(
            code=code, deleted=False,
            defaults={"name": name, "created_by": "migration", "modified_by": "migration"},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('food_labels', '0038_pg_trgm_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='reference_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='reference_amount_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='food_labels.unit'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='total_size_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='food_labels.unit'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='total_size_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=256, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted_datetime', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'locations',
                'managed': True,
                'unique_together': {('code', 'deleted'), ('name', 'deleted')},
            },
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='food_labels.location'),
        ),
        migrations.RunPython(seed_locations, migrations.RunPython.noop),
    ]
