from django.core.management.base import BaseCommand
from django.db import transaction
from flaime_py.food_labels.models import (
    StoreProduct,
    Store,
    Unit,
    Nutrient,
    StoreProductNutritionFact,
    StoreProductImage,
    Source,
    VerifiedNftIngredients,
)
import pandas as pd
import numpy as np
import re
import os
import logging
import subprocess

# TODO: This needs to create a scrape_batch for the added products


logger = logging.getLogger(__name__)

UNIT_NAME_MAP = {
    "µg": "ug",          # Normalize micrograms
    "mcg": "ug",          # Normalize micrograms
    "μg": "ug",          # Another unicode variant
    "mcg DFE": "ug DFE",     # DFE (Dietary Folate Equivalent) units
    "µg DFE": "ug DFE",      # Another DFE variant
}


class Command(BaseCommand):
    help = "Import store products and nutrition facts from spreadsheets"

    def add_arguments(self, parser):
        parser.add_argument("file_path", type=str, help="Path to the Excel/CSV file")
        parser.add_argument(
            "--store",
            type=str,
            required=True,
            help="Store name to associate with products",
        )
        parser.add_argument(
            "--source", type=str, required=True, help="Source name for the data"
        )
        parser.add_argument("--sheet", type=str, help="Sheet name for Excel files")
        parser.add_argument(
            "--validate-only",
            action="store_true",
            help="Only validate without importing",
        )
        parser.add_argument(
            "--update", action="store_true", help="Update existing records"
        )
        parser.add_argument(
            "--create-store",
            action="store_true",
            help="Create store if it does not exist",
        )
        parser.add_argument(
            "--create-source",
            action="store_true",
            help="Create source if it does not exist",
        )
        parser.add_argument(
            '--created-by', type=str, 
            help='Username for the created_by field. Use "auto" to use git revision.',
        )
        parser.add_argument(
            "--supplemented-food",
            action="store_true",
            help="Set supplemented_food flag to True",
        )
        parser.add_argument(
            "--images-file",
            type=str,
            help="Text file with image paths (generated by ls command)",
        )
        parser.add_argument(
            "--default-image-label",
            type=str,
            default="product",
            help="Default label for images when not specified",
        )
        parser.add_argument(
            "--image-base-url",
            type=str,
            help="Base URL or path to prepend to image paths",
        )
        parser.add_argument(
            "--skip-image-validation",
            action="store_true",
            help="Skip validation check requiring each product to have images",
        )

    def handle(self, *args, **options):
        file_path = options["file_path"]
        store_name = options["store"]
        source_name = options["source"]
        created_by = options.get("created_by")

        # Store command options for use in other methods
        self.command_options = options

        # Auto-detect git revision if created_by is set to 'auto'
        if created_by == 'auto':
            created_by = f"import-script-{get_git_revision()}"
            self.stdout.write(f"Auto-detected created_by: {created_by}")

        self.stdout.write(f"Processing {file_path} for store {store_name}")

        # Ensure store exists or create it
        try:
            store = Store.objects.get(name=store_name)
            self.stdout.write(f"Using existing store: {store_name}")
        except Store.DoesNotExist:
            if options.get("create_store"):
                store = Store.objects.create(name=store_name, created_by=created_by)
                self.stdout.write(
                    self.style.SUCCESS(f"Created new store: {store_name}")
                )
            else:
                self.stdout.write(
                    self.style.ERROR(
                        f'Store "{store_name}" does not exist. Use --create-store to create it.'
                    )
                )
                return

        # Ensure source exists or create it
        try:
            source = Source.objects.get(name=source_name)
            self.stdout.write(f"Using existing source: {source_name}")
        except Source.DoesNotExist:
            if options.get("create_source"):
                source = Source.objects.create(name=source_name, created_by=created_by)
                self.stdout.write(
                    self.style.SUCCESS(f"Created new source: {source_name}")
                )
            else:
                self.stdout.write(
                    self.style.ERROR(
                        f'Source "{source_name}" does not exist. Use --create-source to create it.'
                    )
                )
                return

        # Load data to dataframe
        try:
            if file_path.endswith(".xlsx"):
                if options["sheet"]:
                    df = pd.read_excel(file_path, sheet_name=options["sheet"])
                else:
                    df = pd.read_excel(file_path)
            else:
                df = pd.read_csv(file_path)

            # Replace NaN with None
            df = df.replace({np.nan: None})

            self.stdout.write(f"Loaded {len(df)} rows")
        except Exception as e:
            self.stdout.write(self.style.ERROR(f"Error loading file: {e}"))
            return

        # Prepare nutrient mapping
        nutrient_mapping = self.prepare_nutrient_mapping(df.columns)

        # Get units
        self.units = {unit.name: unit for unit in Unit.objects.all()}

        # Prepare image mapping if images file is provided
        images_mapping = None
        if options.get("images_file"):
            images_mapping = self.prepare_images_mapping(
                options.get("images_file"),
                options.get("default_image_label")
            )
            if images_mapping:
                self.stdout.write(f"Found images for {len(images_mapping)} products")

        # Validation
        self.stdout.write("Validating data...")
        validation_errors = self.validate_data(df, nutrient_mapping)

        if validation_errors:
            self.stdout.write(self.style.ERROR("Validation failed:"))
            for error in validation_errors:
                self.stdout.write(f"  - {error}")
            return

        self.stdout.write(self.style.SUCCESS("Validation passed"))

        if options["validate_only"]:
            return

        # Import data
        with transaction.atomic():
            imported, updated = self.import_data(
                df, store, source, nutrient_mapping, options["update"], images_mapping
            )
            self.stdout.write(
                self.style.SUCCESS(
                    f"Successfully imported {imported} new products and updated {updated} existing products"
                )
            )

    def prepare_nutrient_mapping(self, columns):
        """Map column names to nutrient objects and their units"""
        # Get all nutrients from database
        all_nutrients = list(Nutrient.objects.all())

        # Initialize mapping
        nutrient_mapping = {}
        
        # Create a mapping dictionary for nutrient name normalization
        nutrient_name_map = {
            # Common names to database names
            "CALORIES": "ENERGY (KILOCALORIES)",
            "TOTAL FAT": "FAT (TOTAL LIPIDS)",
            "FAT": "FAT (TOTAL LIPIDS)",
            "CARBOHYDRATE": "CARBOHYDRATE, TOTAL (BY DIFFERENCE)",
            "SUGARS": "SUGARS, TOTAL",
            "CARBOHYDRATE SUGARS": "SUGARS, TOTAL",
            "DIETARY FIBER": "FIBRE, TOTAL DIETARY",
            "SATURATED FAT": "FATTY ACIDS, SATURATED, TOTAL",
            "TRANS FAT": "FATTY ACIDS, TRANS, TOTAL",
            "VITAMIN A": "VITAMIN A (MICROGRAMS)",
            "VITAMIN B6": "VITAMIN B-6",
            "VITAMIN B12": "VITAMIN B-12",
            "VITAMIN B-12": "VITAMIN B-12",
            "VITAMIN D": "VITAMIN D (D2 + D3)",
            "VITAMIN E": "ALPHA-TOCOPHEROL",
            "VITAMIN C": "VITAMIN C",
            "FOLATE": "TOTAL FOLACIN",
            "PANTOTHENATE": "PANTOTHENIC ACID",
            "SUGAR ALCOHOL": "SUGAR_ALCOHOLS",
            "ERYTHRITOL": "ERYTHRITOL",
            "L-LEUCINE": "LEUCINE",
            "L-ISOLEUCINE": "ISOLEUCINE",
            "L-VALINE": "VALINE",
            "PROTEIN": "PROTEIN",
            "TAURINE": "TAURINE",
            "NIACIN": "TOTAL NIACIN EQUIVALENT",
        }

        # Define patterns to extract nutrient data from column names
        nutrient_pattern = r"(?P<nutrient>[\w\s\-]+)(?:\s+Unit)?$"
        supplemented_pattern = r"Supplemented with (?P<nutrient>[\w\s\-]+)(?:\s+Unit)?$"

        # Group columns by nutrient
        for column in columns:
            # Skip non-nutrient columns
            if column in [
                "Product ID",
                "Product Name",
                "UPC",
                "Ingredients (en)",
                "Ingredients (fr)",
                "%DV Footnote",
                "Measure Description",
                "Portion",
                "Portion Unit",
                "Additional Notes",
            ]:
                continue

            # Check if it's a nutrient column (not a unit column)
            if "Unit" not in column and "DV" not in column:
                is_supplemented = False
                nutrient_name = None

                # Check if this is a supplemented nutrient
                if column.startswith("Supplemented with "):
                    match = re.match(supplemented_pattern, column)
                    if match:
                        nutrient_name = match.group("nutrient").strip()
                        is_supplemented = True
                else:
                    # Regular nutrient column
                    match = re.match(nutrient_pattern, column)
                    if match:
                        nutrient_name = match.group("nutrient").strip()

                if nutrient_name:
                    # Find corresponding unit and DV columns
                    if is_supplemented:
                        unit_column = (
                            f"Supplemented with {nutrient_name} Unit"
                            if f"Supplemented with {nutrient_name} Unit" in columns
                            else None
                        )
                        dv_column = (
                            f"Supplemented with {nutrient_name} DV"
                            if f"Supplemented with {nutrient_name} DV" in columns
                            else None
                        )
                    else:
                        unit_column = (
                            f"{nutrient_name} Unit"
                            if f"{nutrient_name} Unit" in columns
                            else None
                        )
                        dv_column = (
                            f"{nutrient_name} DV"
                            if f"{nutrient_name} DV" in columns
                            else None
                        )

                    # Normalize nutrient name using the mapping
                    normalized_name = nutrient_name_map.get(nutrient_name.upper(), nutrient_name)
                    
                    # Find matching nutrient in database
                    matching_nutrient = next(
                        (
                            n
                            for n in all_nutrients
                            if n.name.upper() == normalized_name.upper()
                        ),
                        None,
                    )

                    if matching_nutrient:
                        nutrient_mapping[column] = {
                            "nutrient": matching_nutrient,
                            "unit_column": unit_column,
                            "dv_column": dv_column,
                            "is_supplemented": is_supplemented
                        }
                    else:
                        # Log unmapped nutrients
                        logger.warning(f"Couldn't find nutrient for column: {column}")

        return nutrient_mapping

    def prepare_images_mapping(self, images_file=None, default_label="product"):
        """Create a mapping of product IDs to their images"""
        if not images_file:
            return None
        
        images_mapping = {}
        
        if not os.path.isfile(images_file):
            self.stdout.write(self.style.ERROR(f"Images file {images_file} not found"))
            return None
        
        with open(images_file, 'r') as f:
            current_product = None
            image_number = 1
            
            for line in f:
                line = line.strip()
                
                # Skip empty lines
                if not line:
                    continue
                
                # Check if this is a product directory line (number followed by colon)
                product_dir_match = re.match(r'^(\d+):$', line)
                if product_dir_match:
                    current_product = product_dir_match.group(1)
                    if current_product not in images_mapping:
                        images_mapping[current_product] = []
                    image_number = 1
                    continue
                
                # If we have a current product and this line is a filename
                if current_product and re.match(r'^[\w-]+\.(jpg|jpeg|png|gif|webp|JPG|JPEG|PNG|GIF|WEBP)$', line, re.IGNORECASE):
                    filename = line
                    
                    # Determine label based on filename
                    label = default_label
                    label_patterns = {
                        "front": r"front|package|primary",
                        "back": r"back|reverse|nutrition",
                        "ingredients": r"ingredient",
                        "side": r"side"
                    }
                    
                    for lbl, pattern in label_patterns.items():
                        if re.search(pattern, filename.lower()):
                            label = lbl
                            break
                    
                    # Construct relative path
                    rel_path = os.path.join(current_product, filename)
                    
                    images_mapping[current_product].append({
                        "path": rel_path,
                        "label": label,
                        "number": image_number
                    })
                    
                    image_number += 1
        
        return images_mapping

    def validate_data(self, df, nutrient_mapping):
        errors = []

        # Check required columns
        required_columns = ["Product ID", "UPC"]
        for col in required_columns:
            if col not in df.columns:
                errors.append(f"Missing required column: {col}")

        # Check portion unit if portion exists
        if "Portion" in df.columns and "Portion Unit" not in df.columns:
            errors.append("Missing Portion Unit column")

        # Validate units
        unit_columns = [
            info["unit_column"]
            for info in nutrient_mapping.values()
            if info["unit_column"]
        ]
        unique_units = set()

        for unit_col in unit_columns:
            if unit_col in df.columns:
                units = set(df[unit_col].dropna())
                # Normalize units
                normalized_units = set()
                for unit in units:
                    normalized_unit = UNIT_NAME_MAP.get(unit, unit)
                    normalized_units.add(normalized_unit)
                unique_units.update(normalized_units)

        # Check if all units exist in database
        missing_units = [unit for unit in unique_units if unit not in self.units]
        if missing_units:
            errors.append(
                f'Found {len(missing_units)} unknown units: {", ".join(missing_units)}'
            )

        # Check for unmapped nutrient columns
        possible_nutrient_columns = []
        skip_columns = [
            "Product ID",
            "Product Name",
            "UPC",
            "Ingredients (en)",
            "Ingredients (fr)",
            "%DV Footnote",
            "Measure Description",
            "Portion",
            "Portion Unit",
            "Additional Notes",
        ]

        # Find columns that might be nutrients but aren't mapped
        for column in df.columns:
            if column in skip_columns:
                continue
            if "Unit" in column or column.endswith("DV"):
                continue

            # Check if this column is not in the nutrient mapping
            if column not in nutrient_mapping:
                possible_nutrient_columns.append(column)

        if possible_nutrient_columns:
            errors.append(
                f"Found {len(possible_nutrient_columns)} unmapped nutrient columns:"
            )
            for col in possible_nutrient_columns:
                errors.append(f"  - {col} (not found in database)")

        # Check if images are required but missing (only if not skipping image validation)
        if self.command_options.get("images_file") and not self.command_options.get("skip_image_validation"):
            # Get the image mapping if it exists
            images_mapping = self.prepare_images_mapping(
                self.command_options.get("images_file"),
                self.command_options.get("default_image_label")
            )
            
            if images_mapping:
                # Check if each product has at least one image
                products_missing_images = []
                for _, row in df.iterrows():
                    product_id = str(row["Product ID"]) if pd.notna(row["Product ID"]) else None
                    if product_id and product_id not in images_mapping:
                        products_missing_images.append(product_id)
                
                if products_missing_images:
                    errors.append(f"Found {len(products_missing_images)} products without any images:")
                    # Limit the list to first 10 to avoid excessive output
                    for product_id in products_missing_images[:10]:
                        errors.append(f"  - Product ID: {product_id}")
                    
                    if len(products_missing_images) > 10:
                        errors.append(f"  - ... and {len(products_missing_images) - 10} more")
            else:
                errors.append("No valid image mapping could be created from the provided images file")

        return errors

    def import_data(self, df, store, source, nutrient_mapping, update, images_mapping=None):
        imported_count = 0
        updated_count = 0
        created_by = self.command_options.get("created_by")
        supplemented_food = self.command_options.get("supplemented_food", False)

        for _, row in df.iterrows():
            external_id = (
                str(row["Product ID"]) if pd.notna(row["Product ID"]) else None
            )
            upc = str(row["UPC"]) if pd.notna(row["UPC"]) else None

            if not external_id:
                self.stdout.write(
                    self.style.WARNING("Skipping row with no Product ID")
                )
                continue

            # Prepare store product data
            store_product_data = {
                "store": store,
                "source": source,
                "external_id": external_id,
                "site_name": row.get("Product Name"),
                "raw_upc": upc,
                "ingredient_en": row.get("Ingredients (en)"),
                "ingredient_fr": row.get("Ingredients (fr)"),
                "supplemented_food": supplemented_food,
                "verified": True,
                "nutrition_available_flag": True,
                "verified_nft_ingredients": VerifiedNftIngredients.OCR_UNVERIFIED,
                "raw_serving_size": row.get("Measure Description"),
            }

            # Set created_by if provided
            if created_by:
                store_product_data["created_by"] = created_by

            # Get serving size info
            if "Portion" in row and pd.notna(row["Portion"]):
                store_product_data["serving_size"] = row["Portion"]

                if "Portion Unit" in row and pd.notna(row["Portion Unit"]):
                    unit_name = row["Portion Unit"]
                    if unit_name in self.units:
                        store_product_data["serving_size_unit"] = self.units[unit_name]

            # Check if the product already exists
            existing_product = None
            if update:
                existing_product = StoreProduct.objects.filter(
                    store=store, external_id=external_id, deleted=False
                ).first()

            if existing_product and update:
                # Update existing product
                for key, value in store_product_data.items():
                    setattr(existing_product, key, value)
                existing_product.save()
                store_product = existing_product
                updated_count += 1
            else:
                # Create new product
                store_product = StoreProduct.objects.create(**store_product_data)
                imported_count += 1

            # Import nutrition facts
            self.import_nutrition_facts(row, store_product, nutrient_mapping)
            
            # Import images if available
            if images_mapping and external_id in images_mapping:
                image_base_url = self.command_options.get("image_base_url", "")
                self.import_product_images(store_product, images_mapping[external_id], image_base_url, created_by)

        return imported_count, updated_count

    def import_product_images(self, store_product, images, base_url=None, created_by=None):
        """Import images for a store product"""
        # Delete existing images if updating
        if self.command_options.get("update"):
            StoreProductImage.objects.filter(store_product=store_product).delete()
            
        # Import each image
        for image in images:
            # Combine the base URL with the image path if provided
            if base_url:
                image_path = os.path.join(base_url, image["path"])
            else:
                image_path = image["path"]
                
            # Create the image record
            image_data = {
                "store_product": store_product,
                "label": image["label"],
                "number": image["number"],
                "image_path": image_path
            }
            
            # Set created_by if provided
            if created_by:
                image_data["created_by"] = created_by
                
            StoreProductImage.objects.create(**image_data)
            
    def import_nutrition_facts(self, row, store_product, nutrient_mapping):
        # Delete existing nutrition facts
        StoreProductNutritionFact.objects.filter(store_product=store_product).delete()

        # Import each nutrient
        for column, mapping in nutrient_mapping.items():
            nutrient = mapping["nutrient"]
            unit_column = mapping["unit_column"]
            dv_column = mapping["dv_column"]
            is_supplemented = mapping.get("is_supplemented", False)

            # Skip if value is not present
            if column not in row or pd.isna(row[column]):
                continue

            amount = row[column]

            # Get unit if available
            unit = None
            if unit_column and unit_column in row and pd.notna(row[unit_column]):
                unit_name = row[unit_column]
                # Normalize unit name
                unit_name = UNIT_NAME_MAP.get(unit_name, unit_name)
                
                if unit_name in self.units:
                    unit = self.units[unit_name]

            # Get daily value if available
            daily_value = None
            if dv_column and dv_column in row and pd.notna(row[dv_column]):
                daily_value = row[dv_column]

            # Create nutrition fact
            StoreProductNutritionFact.objects.create(
                store_product=store_product,
                nutrient=nutrient,
                amount=amount,
                amount_unit=unit,
                daily_value=daily_value,
                supplemented=is_supplemented,
            )


def get_git_revision():
    """Get the current git revision SHA"""
    try:
        # Get the full SHA
        sha = subprocess.check_output(
            ['git', 'rev-parse', 'HEAD'],
            stderr=subprocess.STDOUT,
            universal_newlines=True
        ).strip()
        
        # Get if there are uncommitted changes
        status = subprocess.check_output(
            ['git', 'status', '--porcelain'],
            stderr=subprocess.STDOUT,
            universal_newlines=True
        ).strip()
        
        if status:
            return f"{sha[:8]}-dirty"
        return sha[:8]  # Return shortened SHA
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown-revision"